### ISSUE TITLE
Final call

### ISSUE THREAD

**Issue by Shemplo** [Shemplo/KSE-and-Digital-Methods#78]
Курсовой проект подъехал, задание появится до конца недели
Строить планов нет смысла, видимо, опять я один всё и сделаю 
(вот хоть у кого-нибудь бы проснулась совесть)

**Comment by Shemplo** [comment]
Графики `X(z)` и `T(z)` можно объединить в один

**Comment by egormkn** [comment]
Окончательно переписал интерфейс :relaxed:
![screenshot](https://user-images.githubusercontent.com/7170781/52012326-5c8a6900-24eb-11e9-8eb7-f470ff255f70.png)
Теперь разбираюсь с расчётами. Надо ещё понять, как правильно запустить таск в отдельном потоке и как скармливать данные графикам через Observable.
